---
#This task is used to set up wordpress.
- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=/srv/wordpress

- name: Add group "wordpress"
  group:
    name: wordpress

- name: Add user "wordpress"
  user:
    name: wordpress
    group: wordpress
    home: /srv/wordpress/

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no

- name: Copy WordPress config file
  template:
    src: wp-config.php
    dest: /srv/wordpress/

- name: Change ownership of WordPress installation
  file:
    path: /srv/wordpress/
    owner: wordpress
    group: wordpress
    state: directory
    recurse: yes
